const DISTRICT = [
  {id: 1, name: "Quận 1", province: 1},
  {id: 2, name: "Quận 2", province: 1},
  {id: 3, name: "Quận 3", province: 1},
  {id: 4, name: "Quận 4", province: 1},
  {id: 5, name: "Quận 5", province: 1},
  {id: 6, name: "Quận 6", province: 1},
  {id: 7, name: "Quận 7", province: 1},
  {id: 8, name: "Quận 8", province: 1},
  {id: 9, name: "Quận 9", province: 1},
  {id: 10, name: "Quận 10", province: 1},
  {id: 11, name: "Quận 11", province: 1},
  {id: 12, name: "Quận 12", province: 1},
  {id: 13, name: "Quận Phú Nhuận", province: 1},
  {id: 14, name: "Quận Bình Thạnh", province: 1},
  {id: 15, name: "Quận Tân Bình", province: 1},
  {id: 16, name: "Quận Tân Phú", province: 1},
  {id: 17, name: "Quận Gò Vấp", province: 1},
  {id: 18, name: "Quận Thủ Đức", province: 1},
  {id: 19, name: "Quận Bình Tân", province: 1},
  {id: 20, name: "Huyện Bình Chánh", province: 1},
  {id: 703, name: "Huyện Hóc Môn", province: 1},
  {id: 704, name: "Huyện Cần Giờ", province: 1},
  {id: 705, name: "Huyện Củ Chi", province: 1},
  {id: 713, name: "Huyện Nhà Bè", province: 1},
  {id: 21, name: "Quận Ba Đình", province: 2},
  {id: 22, name: "Quận Hoàn Kiếm", province: 2},
  {id: 23, name: "Quận Hai Bà Trưng", province: 2},
  {id: 24, name: "Quận Đống Đa", province: 2},
  {id: 25, name: "Quận Tây Hồ", province: 2},
  {id: 26, name: "Quận Cầu Giấy", province: 2},
  {id: 27, name: "Quận Thanh Xuân", province: 2},
  {id: 28, name: "Quận Hoàng Mai", province: 2},
  {id: 29, name: "Quận Long Biên", province: 2},
  {id: 30, name: "Quận Nam Từ Liêm", province: 2},
  {id: 31, name: "Huyện Thanh Trì", province: 2},
  {id: 32, name: "Huyện Gia Lâm", province: 2},
  {id: 33, name: "Huyện Đông Anh", province: 2},
  {id: 34, name: "Huyện Sóc Sơn", province: 2},
  {id: 265, name: "Quận Hà Đông", province: 2},
  {id: 266, name: "Thị xã Sơn Tây", province: 2},
  {id: 267, name: "Huyện Ba Vì", province: 2},
  {id: 268, name: "Huyện Phúc Thọ", province: 2},
  {id: 269, name: "Huyện Thạch Thất", province: 2},
  {id: 270, name: "Huyện Quốc Oai", province: 2},
  {id: 271, name: "Huyện Chương Mỹ", province: 2},
  {id: 272, name: "Huyện Đan Phượng", province: 2},
  {id: 273, name: "Huyện Hoài Đức", province: 2},
  {id: 274, name: "Huyện Thanh Oai", province: 2},
  {id: 275, name: "Huyện Mỹ Đức", province: 2},
  {id: 276, name: "Huyện Ứng Hòa", province: 2},
  {id: 277, name: "Huyện Thường Tín", province: 2},
  {id: 278, name: "Huyện Phú Xuyên", province: 2},
  {id: 716, name: "Huyện Mê Linh", province: 2},
  {id: 749, name: "Quận Bắc Từ Liêm", province: 2},
  {id: 66, name: "Thành phố Châu Đốc", province: 3},
  {id: 67, name: "Thành phố Long Xuyên", province: 3},
  {id: 68, name: "Huyện An Phú", province: 3},
  {id: 69, name: "Thị xã Tân Châu", province: 3},
  {id: 70, name: "Huyện Phú Tân", province: 3},
  {id: 71, name: "Huyện Tịnh Biên", province: 3},
  {id: 72, name: "Huyện Tri Tôn", province: 3},
  {id: 73, name: "Huyện Châu Phú", province: 3},
  {id: 74, name: "Huyện Chợ Mới", province: 3},
  {id: 75, name: "Huyện Châu Thành", province: 3},
  {id: 76, name: "Huyện Thoại Sơn", province: 3},
  {id: 127, name: "Thành phố Bắc Kạn", province: 5},
  {id: 128, name: "Huyện Chợ Đồn", province: 5},
  {id: 129, name: "Huyện Bạch Thông", province: 5},
  {id: 130, name: "Huyện Na Rì", province: 5},
  {id: 131, name: "Huyện Ngân Sơn", province: 5},
  {id: 132, name: "Huyện Ba Bể", province: 5},
  {id: 133, name: "Huyện Chợ Mới", province: 5},
  {id: 134, name: "Huyện Pắc Nặm", province: 5},
  {id: 135, name: "Thành phố Bắc Giang", province: 6},
  {id: 136, name: "Huyện Yên Thế", province: 6},
  {id: 137, name: "Huyện Sơn Động", province: 6},
  {id: 138, name: "Huyện Lục Ngạn", province: 6},
  {id: 139, name: "Huyện Lục Nam", province: 6},
  {id: 140, name: "Huyện Tân Yên", province: 6},
  {id: 141, name: "Huyện Hiệp Hòa", province: 6},
  {id: 142, name: "Huyện Lạng Giang", province: 6},
  {id: 143, name: "Huyện Việt Yên", province: 6},
  {id: 144, name: "Huyện Yên Dũng", province: 6},
  {id: 121, name: "Thành phố Bạc Liêu", province: 7},
  {id: 122, name: "Huyện Vĩnh Lợi", province: 7},
  {id: 123, name: "Huyện Hồng Dân", province: 7},
  {id: 124, name: "Huyện Giá Rai", province: 7},
  {id: 125, name: "Huyện Phước Long", province: 7},
  {id: 126, name: "Huyện Đông Hải", province: 7},
  {id: 721, name: "Huyện Hòa Bình", province: 7},
  {id: 145, name: "Thành phố Bắc Ninh", province: 8},
  {id: 146, name: "Huyện Yên Phong", province: 8},
  {id: 147, name: "Huyện Tiên Du", province: 8},
  {id: 148, name: "Huyện Quế Võ", province: 8},
  {id: 149, name: "Thị xã Từ Sơn", province: 8},
  {id: 150, name: "Huyện Thuận Thành", province: 8},
  {id: 151, name: "Huyện Gia Bình", province: 8},
  {id: 152, name: "Huyện Lương Tài", province: 8},
  {id: 153, name: "Thành phố Bến Tre", province: 9},
  {id: 154, name: "Huyện Chợ Lách", province: 9},
  {id: 155, name: "Huyện Châu Thành", province: 9},
  {id: 156, name: "Huyện Mỏ Cày Bắc", province: 9},
  {id: 157, name: "Huyện Giồng Trôm", province: 9},
  {id: 158, name: "Huyện Bình Đại", province: 9},
  {id: 159, name: "Huyện Ba Tri", province: 9},
  {id: 160, name: "Huyện Thạnh Phú", province: 9},
  {id: 722, name: "Huyện Mỏ Cày Nam", province: 9},
  {id: 109, name: "Thành phố Quy Nhơn", province: 11},
  {id: 110, name: "Huyện An Lão", province: 11},
  {id: 112, name: "Huyện Hoài Ân", province: 11},
  {id: 113, name: "Huyện Hoài Nhơn", province: 11},
  {id: 114, name: "Huyện Phù Mỹ", province: 11},
  {id: 115, name: "Huyện Phù Cát", province: 11},
  {id: 116, name: "Huyện Vĩnh Thạnh", province: 11},
  {id: 117, name: "Huyện Tây Sơn", province: 11},
  {id: 118, name: "Huyện Vân Canh", province: 11},
  {id: 119, name: "Thị xã An Nhơn", province: 11},
  {id: 120, name: "Huyện Tuy Phước", province: 11},
  {id: 92, name: "Thị xã Đồng Xoài", province: 12},
  {id: 93, name: "Huyện Đồng Phù", province: 12},
  {id: 94, name: "Huyện Chơn Thành", province: 12},
  {id: 95, name: "Thị xã Bình Long", province: 12},
  {id: 96, name: "Huyện Lộc Ninh", province: 12},
  {id: 97, name: "Huyện Bù Đốp", province: 12},
  {id: 98, name: "Thị xã Phước Long", province: 12},
  {id: 99, name: "Huyện Bù Đăng", province: 12},
  {id: 723, name: "Huyện Bù Gia Mập", province: 12},
  {id: 724, name: "Huyện Hớn Quản", province: 12},
  {id: 756, name: "Huyện Phú Riềng", province: 12},
  {id: 100, name: "Thành phố Phan Thiết", province: 13},
  {id: 101, name: "Huyện Tuy Phong", province: 13},
  {id: 102, name: "Huyện Bắc Bình", province: 13},
  {id: 103, name: "Huyện Hàm Thuận Bắc", province: 13},
  {id: 104, name: "Huyện Hàm Thuận Nam", province: 13},
  {id: 105, name: "Huyện Hàm Tân", province: 13},
  {id: 106, name: "Huyện Đức Linh", province: 13},
  {id: 107, name: "Huyện Tánh Linh", province: 13},
  {id: 108, name: "Huyện Phú Quí", province: 13},
  {id: 719, name: "Thị xã La Gi", province: 13},
  {id: 182, name: "Thành phố Cà Mau", province: 14},
  {id: 183, name: "Huyện Cái Nước", province: 14},
  {id: 184, name: "Huyện Trần Văn Thời", province: 14},
  {id: 185, name: "Huyện U Minh", province: 14},
  {id: 186, name: "Huyện Thới Bình", province: 14},
  {id: 187, name: "Huyện Đầm Dơi", province: 14},
  {id: 188, name: "Huyện Ngọc Hiển", province: 14},
  {id: 189, name: "Huyện Năm Căn", province: 14},
  {id: 190, name: "Huyện Phú Tân", province: 14},
  {id: 174, name: "Quận Bình Thủy", province: 15},
  {id: 175, name: "Quận Ninh Kiều", province: 15},
  {id: 176, name: "Quận Cái Răng", province: 15},
  {id: 177, name: "Quận Ô Môn", province: 15},
  {id: 178, name: "Huyện Phong Điền", province: 15},
  {id: 179, name: "Huyện Cờ Đỏ", province: 15},
  {id: 180, name: "Huyện Vĩnh Thạnh", province: 15},
  {id: 181, name: "Quận Thốt Nốt", province: 15},
  {id: 725, name: "Huyện Thới Lai", province: 15},
  {id: 161, name: "Thành phố Cao Bằng", province: 16},
  {id: 162, name: "Huyện Trùng Khánh", province: 16},
  {id: 163, name: "Huyện Bảo Lạc", province: 16},
  {id: 164, name: "Huyện Thông Nông", province: 16},
  {id: 165, name: "Huyện Hà Quảng", province: 16},
  {id: 166, name: "Huyện Trà Lĩnh", province: 16},
  {id: 167, name: "Huyện Nguyên Bình", province: 16},
  {id: 168, name: "Huyện Hòa An", province: 16},
  {id: 169, name: "Huyện Quảng Uyên", province: 16},
  {id: 170, name: "Huyện Thạch An", province: 16},
  {id: 171, name: "Huyện Hạ Lang", province: 16},
  {id: 172, name: "Huyện Bảo Lâm", province: 16},
  {id: 173, name: "Huyện Phục Hòa", province: 16},
  {id: 42, name: "Quận Hải Châu", province: 17},
  {id: 43, name: "Quận Thanh Khê", province: 17},
  {id: 44, name: "Quận Ngũ Hành Sơn", province: 17},
  {id: 46, name: "Quận Sơn Trà", province: 17},
  {id: 47, name: "Quận Liên Chiểu", province: 17},
  {id: 48, name: "Quận Cẩm Lệ", province: 17},
  {id: 49, name: "Huyện Hòa Vang", province: 17},
  {id: 191, name: "Thành Phố Buôn Ma Thuột", province: 18},
  {id: 192, name: "Huyện Cư MGar", province: 18},
  {id: 193, name: "Huyện Krông Búk", province: 18},
  {id: 194, name: "Huyện Ea H'leo", province: 18},
  {id: 195, name: "Huyện Krông Năng", province: 18},
  {id: 196, name: "Huyện Ea Súp", province: 18},
  {id: 197, name: "Huyện Krông Pắc", province: 18},
  {id: 198, name: "Huyện Ea Kar", province: 18},
  {id: 199, name: "Huyện M'đrắk", province: 18},
  {id: 200, name: "Huyện Krông Ana", province: 18},
  {id: 201, name: "Huyện Krông Bông", province: 18},
  {id: 202, name: "Huyện Lăk", province: 18},
  {id: 203, name: "Huyện Buôn Đôn", province: 18},
  {id: 717, name: "Thị xã Buôn Hồ", province: 18},
  {id: 726, name: "Huyện Cư Kuin", province: 18},
  {id: 694, name: "Thành phố Điện Biên Phủ", province: 19},
  {id: 695, name: "Thị xã Mường Lay", province: 19},
  {id: 696, name: "Huyện Mường Chà", province: 19},
  {id: 697, name: "Huyện Mường Nhé", province: 19},
  {id: 698, name: "Huyện Mường Ảng", province: 19},
  {id: 699, name: "Huyện Tuần Giáo", province: 19},
  {id: 700, name: "Huyện Tủa Chùa", province: 19},
  {id: 701, name: "Huyện Điện Biên", province: 19},
  {id: 702, name: "Huyện Điện Biên Đông", province: 19},
  {id: 745, name: "Huyện Nậm Pồ", province: 19},
  {id: 550, name: "Thành phố Biên Hòa", province: 20},
  {id: 551, name: "Huyện Vĩnh Cửu", province: 20},
  {id: 552, name: "Huyện Tân Phú", province: 20},
  {id: 553, name: "Huyện Định Quán", province: 20},
  {id: 554, name: "Huyện Thống Nhất", province: 20},
  {id: 555, name: "Thị xã Long Khánh", province: 20},
  {id: 556, name: "Huyện Xuân Lộc", province: 20},
  {id: 557, name: "Huyện Long Thành", province: 20},
  {id: 558, name: "Huyện Nhơn Trạch", province: 20},
  {id: 559, name: "Huyện Trảng Bom", province: 20},
  {id: 560, name: "Huyện Cẩm Mỹ", province: 20},
  {id: 244, name: "Thành phố Pleiku", province: 21},
  {id: 245, name: "Huyện Chư Păh", province: 21},
  {id: 246, name: "Huyện Mang Yang", province: 21},
  {id: 247, name: "Huyện KBang", province: 21},
  {id: 248, name: "Thị xã An Khê", province: 21},
  {id: 249, name: "Huyện Kông Chro", province: 21},
  {id: 250, name: "Huyện Đức Cơ", province: 21},
  {id: 251, name: "Huyện Chư Prông", province: 21},
  {id: 252, name: "Huyện Chư Sê", province: 21},
  {id: 253, name: "Thị xã AYun Pa", province: 21},
  {id: 254, name: "Huyện Krông Pa", province: 21},
  {id: 255, name: "Huyện Ia Grai", province: 21},
  {id: 256, name: "Huyện Đăk Đoa", province: 21},
  {id: 257, name: "Huyện Ia Pa", province: 21},
  {id: 258, name: "Huyện Đăk Pơ", province: 21},
  {id: 727, name: "Huyện Chư Pưh", province: 21},
  {id: 728, name: "Huyện Phú Thiện", province: 21},
  {id: 302, name: "Thành phố Hà Giang", province: 22},
  {id: 303, name: "Huyện Đồng Văn", province: 22},
  {id: 304, name: "Huyện Mèo Vạc", province: 22},
  {id: 305, name: "Huyện Yên Minh", province: 22},
  {id: 306, name: "Huyện Quản Bạ", province: 22},
  {id: 307, name: "Huyện Vị Xuyên", province: 22},
  {id: 308, name: "Huyện Bắc Mê", province: 22},
  {id: 309, name: "Huyện Hoàng Su Phì", province: 22},
  {id: 310, name: "Huyện Xín Mần", province: 22},
  {id: 311, name: "Huyện Bắc Quang", province: 22},
  {id: 312, name: "Huyện Quang Bình", province: 22},
  {id: 259, name: "Thành phố Phủ Lý", province: 23},
  {id: 260, name: "Huyện Duy Tiên", province: 23},
  {id: 261, name: "Huyện Kim Bảng", province: 23},
  {id: 262, name: "Huyện Lý Nhân", province: 23},
  {id: 263, name: "Huyện Thanh Liêm", province: 23},
  {id: 264, name: "Huyện Bình Lục", province: 23},
  {id: 706, name: "Thành phố Vị Thanh", province: 24},
  {id: 707, name: "Thị xã Ngã Bảy", province: 24},
  {id: 708, name: "Huyện Vị Thủy", province: 24},
  {id: 709, name: "Huyện Long Mỹ", province: 24},
  {id: 710, name: "Huyện Phụng Hiệp", province: 24},
  {id: 711, name: "Huyện Châu Thành", province: 24},
  {id: 712, name: "Huyện Châu Thành A", province: 24},
  {id: 758, name: "Thị xã Long Mỹ", province: 24},
  {id: 279, name: "Thành phố Hà Tĩnh", province: 25},
  {id: 280, name: "Thị xã Hồng Lĩnh", province: 25},
  {id: 281, name: "Huyện Hương Sơn", province: 25},
  {id: 282, name: "Huyện Đức Thọ", province: 25},
  {id: 283, name: "Huyện Nghi Xuân", province: 25},
  {id: 284, name: "Huyện Can Lộc", province: 25},
  {id: 285, name: "Huyện Hương Khê", province: 25},
  {id: 286, name: "Huyện Thạch Hà", province: 25},
  {id: 287, name: "Huyện Cẩm Xuyên", province: 25},
  {id: 288, name: "Huyện Kỳ Anh", province: 25},
  {id: 289, name: "Huyện Vũ Quang", province: 25},
  {id: 729, name: "Huyện Lộc Hà", province: 25},
  {id: 755, name: "Thị xã Kỳ Anh", province: 25},
  {id: 290, name: "Thành phố Hải Dương", province: 26},
  {id: 291, name: "Thị xã Chí Linh", province: 26},
  {id: 292, name: "Huyện Nam Sách", province: 26},
  {id: 293, name: "Huyện Kinh Môn", province: 26},
  {id: 294, name: "Huyện Gia Lộc", province: 26},
  {id: 295, name: "Huyện Tứ Kỳ", province: 26},
  {id: 296, name: "Huyện Thanh Miện", province: 26},
  {id: 297, name: "Huyện Ninh Giang", province: 26},
  {id: 298, name: "Huyện Cẩm Giàng", province: 26},
  {id: 299, name: "Huyện Thanh Hà", province: 26},
  {id: 300, name: "Huyện Kim Thành", province: 26},
  {id: 301, name: "Huyện Bình Giang", province: 26},
  {id: 52, name: "Quận Hồng Bàng", province: 27},
  {id: 53, name: "Quận Lê Chân", province: 27},
  {id: 54, name: "Quận Ngô Quyền", province: 27},
  {id: 55, name: "Quận Kiến An", province: 27},
  {id: 56, name: "Quận Hải An", province: 27},
  {id: 57, name: "Quận Đồ Sơn", province: 27},
  {id: 58, name: "Huyện An Lão", province: 27},
  {id: 59, name: "Huyện Kiến Thụy", province: 27},
  {id: 60, name: "Huyện Thủy Nguyên", province: 27},
  {id: 61, name: "Huyện An Dương", province: 27},
  {id: 62, name: "Huyện Tiên Lãng", province: 27},
  {id: 63, name: "Huyện Vĩnh Bảo", province: 27},
  {id: 64, name: "Huyện Cát Hải", province: 27},
  {id: 65, name: "Huyện Bạch Long Vĩ", province: 27},
  {id: 730, name: "Quận Dương Kinh", province: 27},
  {id: 313, name: "Thành phố Hòa Bình", province: 28},
  {id: 314, name: "Huyện Đà Bắc", province: 28},
  {id: 315, name: "Huyện Mai Châu", province: 28},
  {id: 316, name: "Huyện Tân Lạc", province: 28},
  {id: 317, name: "Huyện Lạc Sơn", province: 28},
  {id: 318, name: "Huyện Kỳ Sơn", province: 28},
  {id: 319, name: "Huyện Lương Sơn", province: 28},
  {id: 340, name: "Huyện Kim Bôi", province: 28},
  {id: 341, name: "Huyện Lạc Thủy", province: 28},
  {id: 342, name: "Huyện Yên Thủy", province: 28},
  {id: 343, name: "Huyện Cao Phong", province: 28},
  {id: 354, name: "Thành phố Nha Trang", province: 30},
  {id: 355, name: "Huyện Vạn Ninh", province: 30},
  {id: 356, name: "Huyện Ninh Hòa", province: 30},
  {id: 357, name: "Huyện Diên Khánh", province: 30},
  {id: 358, name: "Huyện Khánh Vĩnh", province: 30},
  {id: 359, name: "Thành phố Cam Ranh", province: 30},
  {id: 360, name: "Huyện Khánh Sơn", province: 30},
  {id: 731, name: "Huyện Cam Lâm", province: 30},
  {id: 384, name: "Thành phố Lai Châu", province: 32},
  {id: 385, name: "Huyện Tam Đường", province: 32},
  {id: 386, name: "Huyện Phong Thổ", province: 32},
  {id: 387, name: "Huyện Sìn Hồ", province: 32},
  {id: 388, name: "Huyện Mường Tè", province: 32},
  {id: 389, name: "Huyện Than Uyên", province: 32},
  {id: 714, name: "Huyện Tân Uyên", province: 32},
  {id: 715, name: "Huyện Nậm Nhùn", province: 32},
  {id: 399, name: "Thành phố Đà Lạt", province: 33},
  {id: 400, name: "Thành phố Bảo Lộc", province: 33},
  {id: 401, name: "Huyện Đức Trọng", province: 33},
  {id: 402, name: "Huyện Di Linh", province: 33},
  {id: 403, name: "Huyện Đơn Dương", province: 33},
  {id: 404, name: "Huyện Lạc Dương", province: 33},
  {id: 405, name: "Huyện Đạ Huoai", province: 33},
  {id: 406, name: "Huyện Đạ Tẻh", province: 33},
  {id: 407, name: "Huyện Cát Tiên", province: 33},
  {id: 408, name: "Huyện Lâm Hà", province: 33},
  {id: 409, name: "Huyện Bảo lâm", province: 33},
  {id: 410, name: "Huyện Đam Rông", province: 33},
  {id: 411, name: "Thành phố Lạng Sơn", province: 34},
  {id: 412, name: "Huyện Tràng Định", province: 34},
  {id: 413, name: "Huyện Bình Gia", province: 34},
  {id: 414, name: "Huyện Văn Lãng", province: 34},
  {id: 415, name: "Huyện Bắc Sơn", province: 34},
  {id: 416, name: "Huyện Văn Quan", province: 34},
  {id: 417, name: "Huyện Cao Lộc", province: 34},
  {id: 418, name: "Huyện Lộc Bình", province: 34},
  {id: 419, name: "Huyện Chi Lăng", province: 34},
  {id: 420, name: "Huyện Đình Lập", province: 34},
  {id: 421, name: "Huyện Hữu Lũng", province: 34},
  {id: 390, name: "Thành phố Lào Cai", province: 35},
  {id: 391, name: "Huyện Si Ma Cai", province: 35},
  {id: 392, name: "Huyện Bát Xát", province: 35},
  {id: 393, name: "Huyện Bảo Thắng", province: 35},
  {id: 394, name: "Huyện Sa Pa", province: 35},
  {id: 395, name: "Huyện Văn Bàn", province: 35},
  {id: 396, name: "Huyện Bảo Yên", province: 35},
  {id: 397, name: "Huyện Bắc Hà", province: 35},
  {id: 398, name: "Huyện Mường Khương", province: 35},
  {id: 422, name: "Thành phố Tân An", province: 36},
  {id: 423, name: "Huyện Vĩnh Hưng", province: 36},
  {id: 424, name: "Huyện Mộc Hóa", province: 36},
  {id: 425, name: "Huyện Tân Thạnh", province: 36},
  {id: 426, name: "Huyện Thạnh Hóa", province: 36},
  {id: 427, name: "Huyện Đức Huệ", province: 36},
  {id: 428, name: "Huyện Đức Hòa", province: 36},
  {id: 429, name: "Huyện Bến Lức", province: 36},
  {id: 430, name: "Huyện Thủ Thừa", province: 36},
  {id: 431, name: "Huyện Châu Thành", province: 36},
  {id: 432, name: "Huyện Tân Trụ", province: 36},
  {id: 433, name: "Huyện Cần Đước", province: 36},
  {id: 434, name: "Huyện Cần Giuộc", province: 36},
  {id: 435, name: "Huyện Tân Hưng", province: 36},
  {id: 748, name: "Thị xã Kiến Tường", province: 36},
  {id: 454, name: "Thành phố Nam Định", province: 37},
  {id: 455, name: "Huyện Mỹ Lộc", province: 37},
  {id: 456, name: "Huyện Xuân Trường", province: 37},
  {id: 457, name: "Huyện Giao Thủy", province: 37},
  {id: 458, name: "Huyện Ý Yên", province: 37},
  {id: 459, name: "Huyện Vụ Bản", province: 37},
  {id: 460, name: "Huyện Nam Trực", province: 37},
  {id: 461, name: "Huyện Trực Ninh", province: 37},
  {id: 462, name: "Huyện Nghĩa Hưng", province: 37},
  {id: 463, name: "Huyện Hải Hậu", province: 37},
  {id: 464, name: "Thành phố Vinh", province: 38},
  {id: 465, name: "Thị xã Cửa Lò", province: 38},
  {id: 466, name: "Huyện Quỳ Châu", province: 38},
  {id: 467, name: "Huyện Quỳ Hợp", province: 38},
  {id: 468, name: "Huyện Nghĩa Đàn", province: 38},
  {id: 469, name: "Huyện Quỳnh Lưu", province: 38},
  {id: 470, name: "Huyện Kỳ Sơn", province: 38},
  {id: 471, name: "Huyện Tương Dương", province: 38},
  {id: 472, name: "Huyện Con Cuông", province: 38},
  {id: 473, name: "Huyện Tân Kỳ", province: 38},
  {id: 474, name: "Huyện Yên Thành", province: 38},
  {id: 475, name: "Huyện Diễn Châu", province: 38},
  {id: 476, name: "Huyện Anh Sơn", province: 38},
  {id: 477, name: "Huyện Đô Lương", province: 38},
  {id: 478, name: "Huyện Thanh Chương", province: 38},
  {id: 479, name: "Huyện Nghi Lộc", province: 38},
  {id: 480, name: "Huyện Nam Đàn", province: 38},
  {id: 481, name: "Huyện Hưng Nguyên", province: 38},
  {id: 482, name: "Huyện Quế Phong", province: 38},
  {id: 736, name: "Thị xã Thái Hoà", province: 38},
  {id: 747, name: "Thị xã Hoàng Mai", province: 38},
  {id: 483, name: "Thành phố Phan Rang-Tháp Chàm", province: 39},
  {id: 484, name: "Huyện Ninh Sơn", province: 39},
  {id: 485, name: "Huyện Ninh Hải", province: 39},
  {id: 486, name: "Huyện Ninh Phước", province: 39},
  {id: 487, name: "Huyện Bác Ái", province: 39},
  {id: 488, name: "Huyện Thuận Bắc", province: 39},
  {id: 738, name: "Huyện Thuận Nam", province: 39},
  {id: 232, name: "Thành phố Việt Trì", province: 40},
  {id: 233, name: "Thị xã Phú Thọ", province: 40},
  {id: 234, name: "Huyện Đoan Hùng", province: 40},
  {id: 235, name: "Huyện Thanh Ba", province: 40},
  {id: 236, name: "Huyện Hạ Hòa", province: 40},
  {id: 237, name: "Huyện Cẩm Khê", province: 40},
  {id: 238, name: "Huyện Yên Lập", province: 40},
  {id: 239, name: "Huyện Thanh Sơn", province: 40},
  {id: 240, name: "Huyện Phù Ninh", province: 40},
  {id: 241, name: "Huyện Lâm Thao", province: 40},
  {id: 242, name: "Huyện Tam Nông", province: 40},
  {id: 243, name: "Huyện Thanh Thủy", province: 40},
  {id: 734, name: "Huyện Tân Sơn", province: 40},
  {id: 503, name: "Thành phố Tuy Hòa", province: 41},
  {id: 504, name: "Huyện Đồng Xuân", province: 41},
  {id: 505, name: "Thị Xã Sông Cầu", province: 41},
  {id: 506, name: "Huyện Tuy An", province: 41},
  {id: 507, name: "Huyện Sơn Hòa", province: 41},
  {id: 508, name: "Huyện Song Hinh", province: 41},
  {id: 509, name: "Huyện Đông Hòa", province: 41},
  {id: 510, name: "Huyện Phú Hòa", province: 41},
  {id: 511, name: "Huyện Tây Hòa", province: 41},
  {id: 512, name: "Thành phố Đồng Hới", province: 42},
  {id: 513, name: "Huyện Tuyên Hóa", province: 42},
  {id: 514, name: "Huyện Minh Hóa", province: 42},
  {id: 515, name: "Huyện Quảng Trạch", province: 42},
  {id: 516, name: "Huyện Bố Trạch", province: 42},
  {id: 517, name: "Huyện Quảng Ninh", province: 42},
  {id: 518, name: "Huyện Lệ Thủy", province: 42},
  {id: 750, name: "Thị xã Ba Đồn", province: 42},
  {id: 519, name: "Thành phố Tam Kỳ", province: 43},
  {id: 520, name: "Thành phố Hội An", province: 43},
  {id: 521, name: "Huyện Duy Xuyên", province: 43},
  {id: 522, name: "Huyện Điện Bàn", province: 43},
  {id: 523, name: "Huyện Đại Lộc", province: 43},
  {id: 524, name: "Huyện Quế Sơn", province: 43},
  {id: 525, name: "Huyện Hiệp Đức", province: 43},
  {id: 526, name: "Huyện Thăng Bình", province: 43},
  {id: 527, name: "Huyện Núi Thành", province: 43},
  {id: 528, name: "Huyện Tiên Phước", province: 43},
  {id: 529, name: "Huyện Bắc Trà My", province: 43},
  {id: 530, name: "Huyện Đông Giang", province: 43},
  {id: 531, name: "Huyện Nam Giang", province: 43},
  {id: 532, name: "Huyện Phước Sơn", province: 43},
  {id: 533, name: "Huyện Nam Trà My", province: 43},
  {id: 534, name: "Huyện Tây Giang", province: 43},
  {id: 535, name: "Huyện Phú Ninh", province: 43},
  {id: 737, name: "Huyện Nông Sơn", province: 43},
  {id: 536, name: "Thành phố Quảng Ngãi", province: 44},
  {id: 537, name: "Huyện Lý Sơn", province: 44},
  {id: 538, name: "Huyện Bình Sơn", province: 44},
  {id: 539, name: "Huyện Trà Bồng", province: 44},
  {id: 540, name: "Huyện Sơn Tịnh", province: 44},
  {id: 541, name: "Huyện Sơn Hà", province: 44},
  {id: 542, name: "Huyện Tư Nghĩa", province: 44},
  {id: 543, name: "Huyện Nghĩa Hành", province: 44},
  {id: 544, name: "Huyện Minh Long", province: 44},
  {id: 545, name: "Huyện Mộ Đức", province: 44},
  {id: 546, name: "Huyện Đức Phổ", province: 44},
  {id: 547, name: "Huyện Ba Tơ", province: 44},
  {id: 548, name: "Huyện Sơn Tây", province: 44},
  {id: 549, name: "Huyện Tây Trà", province: 44},
  {id: 489, name: "Thành phố Hạ Long", province: 45},
  {id: 490, name: "Thành phố Cẩm Phả", province: 45},
  {id: 491, name: "Thành phố Uông Bí", province: 45},
  {id: 492, name: "Thành phố Móng Cái", province: 45},
  {id: 493, name: "Huyện Bình Liêu", province: 45},
  {id: 494, name: "Huyện Đầm Hà", province: 45},
  {id: 495, name: "Huyện Hải Hà", province: 45},
  {id: 496, name: "Huyện Tiên Yên", province: 45},
  {id: 497, name: "Huyện Ba Chế", province: 45},
  {id: 498, name: "Huyện Đông Triều", province: 45},
  {id: 499, name: "Thị xã Quảng Yên", province: 45},
  {id: 500, name: "Huyện Hoành Bồ", province: 45},
  {id: 501, name: "Huyện Vân Đồn", province: 45},
  {id: 502, name: "Huyện Cô Tô", province: 45},
  {id: 561, name: "Thành phố Đông Hà", province: 46},
  {id: 562, name: "Thị xã Quảng Trị", province: 46},
  {id: 563, name: "Huyện Vĩnh Linh", province: 46},
  {id: 564, name: "Huyện Gio Linh", province: 46},
  {id: 565, name: "Huyện Cam Lộ", province: 46},
  {id: 566, name: "Huyện Triệu Phong", province: 46},
  {id: 567, name: "Huyện Hải Lăng", province: 46},
  {id: 568, name: "Huyện Hướng Hóa", province: 46},
  {id: 569, name: "Huyện Đa Krông", province: 46},
  {id: 570, name: "Huyện Cồn Cỏ", province: 46},
  {id: 571, name: "Thành phố Sóc Trăng", province: 47},
  {id: 572, name: "Huyện Kế Sách", province: 47},
  {id: 573, name: "Huyện Mỹ Tú", province: 47},
  {id: 574, name: "Huyện Mỹ Xuyên", province: 47},
  {id: 575, name: "Huyện Thạnh Trị", province: 47},
  {id: 576, name: "Huyện Long Phú", province: 47},
  {id: 577, name: "Thị xã Vĩnh Châu", province: 47},
  {id: 578, name: "Huyện Cù Lao Dung", province: 47},
  {id: 741, name: "Huyện Châu Thành", province: 47},
  {id: 742, name: "Thị xã Ngã Năm", province: 47},
  {id: 743, name: "Huyện Trần Đề", province: 47},
  {id: 591, name: "Thành phố Tây Ninh", province: 48},
  {id: 592, name: "Huyện Tân Biên", province: 48},
  {id: 593, name: "Huyện Tân Châu", province: 48},
  {id: 594, name: "Huyện Dương Minh Châu", province: 48},
  {id: 595, name: "Huyện Châu Thành", province: 48},
  {id: 596, name: "Huyện Hòa Thành", province: 48},
  {id: 597, name: "Huyện Bến Cầu", province: 48},
  {id: 598, name: "Huyện Gò Dầu", province: 48},
  {id: 599, name: "Huyện Trảng Bàng", province: 48},
  {id: 627, name: "Thành phố Thái Bình", province: 49},
  {id: 628, name: "Huyện Quỳnh Phụ", province: 49},
  {id: 629, name: "Huyện Hưng Hà", province: 49},
  {id: 630, name: "Huyện Đông Hưng", province: 49},
  {id: 631, name: "Huyện Vũ Thư", province: 49},
  {id: 632, name: "Huyện Kiến Xương", province: 49},
  {id: 633, name: "Huyện Tiền Hải", province: 49},
  {id: 634, name: "Huyện Thái Thụy", province: 49},
  {id: 635, name: "Thành phố Thái Nguyên", province: 50},
  {id: 636, name: "Thành phố Sông Công", province: 50},
  {id: 637, name: "Huyện Định Hóa", province: 50},
  {id: 638, name: "Huyện Phú Lương", province: 50},
  {id: 639, name: "Huyện Võ Nhai", province: 50},
  {id: 640, name: "Huyện Đại Từ", province: 50},
  {id: 641, name: "Huyện Đồng Hỷ", province: 50},
  {id: 642, name: "Huyện Phú Bình", province: 50},
  {id: 643, name: "Thị Xã Phổ Yên", province: 50},
  {id: 600, name: "Thành phố Thanh Hóa", province: 51},
  {id: 601, name: "Thị xã Bỉm Sơn", province: 51},
  {id: 602, name: "Thị xã Sầm Sơn", province: 51},
  {id: 603, name: "Huyện Quan Hóa", province: 51},
  {id: 604, name: "Huyện Quan Sơn", province: 51},
  {id: 605, name: "Huyện Mường Lát", province: 51},
  {id: 606, name: "Huyện Bá Thước", province: 51},
  {id: 607, name: "Huyện Thường Xuân", province: 51},
  {id: 608, name: "Huyện Như Xuân", province: 51},
  {id: 609, name: "Huyện Như Thanh", province: 51},
  {id: 610, name: "Huyện Lang Chánh", province: 51},
  {id: 611, name: "Huyện Ngọc Lặc", province: 51},
  {id: 612, name: "Huyện Thạch Thành", province: 51},
  {id: 613, name: "Huyện Cẩm Thủy", province: 51},
  {id: 614, name: "Huyện Thọ Xuân", province: 51},
  {id: 615, name: "Huyện Vĩnh Lộc", province: 51},
  {id: 616, name: "Huyện Thiệu Hóa", province: 51},
  {id: 617, name: "Huyện Triệu Sơn", province: 51},
  {id: 618, name: "Huyện Nông Cống", province: 51},
  {id: 619, name: "Huyện Hà Trung", province: 51},
  {id: 620, name: "Huyện Hoằng Hóa", province: 51},
  {id: 621, name: "Huyện Nga Sơn", province: 51},
  {id: 622, name: "Huyện Hậu Lộc", province: 51},
  {id: 623, name: "Huyện Tĩnh Gia", province: 51},
  {id: 624, name: "Huyện Yên Định", province: 51},
  {id: 625, name: "Huyện Quảng Xương", province: 51},
  {id: 626, name: "Huyện Đông Sơn", province: 51},
  {id: 644, name: "Thành phố Huế", province: 52},
  {id: 645, name: "Huyện Phong Điền", province: 52},
  {id: 646, name: "Huyện Quảng Điền", province: 52},
  {id: 647, name: "Thị xã Hương Trà", province: 52},
  {id: 648, name: "Huyện Phú Vang", province: 52},
  {id: 649, name: "Thị xã Hương Thủy", province: 52},
  {id: 650, name: "Huyện Phú Lộc", province: 52},
  {id: 651, name: "Huyện Nam Đông", province: 52},
  {id: 652, name: "Huyện A Lưới", province: 52},
  {id: 653, name: "Thành phố Mỹ Tho", province: 53},
  {id: 654, name: "Thị xã Gò Công", province: 53},
  {id: 655, name: "Huyện Cái Bè", province: 53},
  {id: 656, name: "Huyện Cai Lậy", province: 53},
  {id: 657, name: "Huyện Châu Thành", province: 53},
  {id: 658, name: "Huyện Chợ Gạo", province: 53},
  {id: 659, name: "Huyện Gò Công Đông", province: 53},
  {id: 660, name: "Huyện Gò Công Tây", province: 53},
  {id: 661, name: "Huyện Tân Phước", province: 53},
  {id: 720, name: "Huyện Tân Phú Đông", province: 53},
  {id: 753, name: "Thị xã Cai Lậy", province: 53},
  {id: 662, name: "Thành phố Trà Vinh", province: 54},
  {id: 663, name: "Huyện Càng Long", province: 54},
  {id: 664, name: "Huyện Cầu Kè", province: 54},
  {id: 665, name: "Huyện Tiểu Cần", province: 54},
  {id: 666, name: "Huyện Châu Thành", province: 54},
  {id: 667, name: "Huyện Trà Cú", province: 54},
  {id: 668, name: "Huyện Cầu Ngang", province: 54},
  {id: 669, name: "Huyện Duyên Hải", province: 54},
  {id: 759, name: "Thị xã Duyên Hải", province: 54},
  {id: 670, name: "Thành phố Tuyên Quang", province: 55},
  {id: 671, name: "Huyện Nà Hang", province: 55},
  {id: 672, name: "Huyện Chiêm Hóa", province: 55},
  {id: 673, name: "Huyện Hàm Yên", province: 55},
  {id: 674, name: "Huyện Yên Sơn", province: 55},
  {id: 675, name: "Huyện Sơn Dương", province: 55},
  {id: 744, name: "Huyện Lâm Bình", province: 55},
  {id: 362, name: "Thành phố Rạch Giá", province: 56},
  {id: 363, name: "Thị xã Hà Tiên", province: 56},
  {id: 364, name: "Huyện Kiên Lương", province: 56},
  {id: 365, name: "Huyện Hòn Đất", province: 56},
  {id: 366, name: "Huyện Tân Hiệp", province: 56},
  {id: 367, name: "Huyện Châu Thành", province: 56},
  {id: 368, name: "Huyện Giồng Riềng", province: 56},
  {id: 369, name: "Huyện Gò Quao", province: 56},
  {id: 370, name: "Huyện An Biên", province: 56},
  {id: 371, name: "Huyện An Minh", province: 56},
  {id: 372, name: "Huyện Vĩnh Thuận", province: 56},
  {id: 373, name: "Huyện Phú Quốc", province: 56},
  {id: 374, name: "Huyện Kiên Hải", province: 56},
  {id: 732, name: "Huyện U Minh Thượng", province: 56},
  {id: 733, name: "Huyện Giang Thành", province: 56},
  {id: 685, name: "Thành phố Vĩnh Yên", province: 57},
  {id: 686, name: "Huyện Tam Dương", province: 57},
  {id: 687, name: "Huyện Lập Thạch", province: 57},
  {id: 688, name: "Huyện Vĩnh Tường", province: 57},
  {id: 689, name: "Huyện Yên Lạc", province: 57},
  {id: 690, name: "Huyện Bình Xuyên", province: 57},
  {id: 692, name: "Thị xã Phúc Yên", province: 57},
  {id: 693, name: "Huyện Tam Đảo", province: 57},
  {id: 735, name: "Huyện Sông Lô", province: 57},
  {id: 77, name: "Thành phố Vũng Tàu", province: 58},
  {id: 78, name: "Thành phố Bà Rịa", province: 58},
  {id: 79, name: "Huyện Xuyên Mộc", province: 58},
  {id: 80, name: "Huyện Long Điền", province: 58},
  {id: 82, name: "Huyện Tân Thành", province: 58},
  {id: 83, name: "Huyện Châu Đức", province: 58},
  {id: 84, name: "Huyện Đất Đỏ", province: 58},
  {id: 754, name: "Huyện Côn Đảo", province: 58},
  {id: 676, name: "Thành phố Yên Bái", province: 59},
  {id: 677, name: "Thị xã Nghĩa Lộ", province: 59},
  {id: 678, name: "Huyện Văn Yên", province: 59},
  {id: 679, name: "Huyện Yên Bình", province: 59},
  {id: 680, name: "Huyện Mù Cang Chải", province: 59},
  {id: 681, name: "Huyện Văn Chấn", province: 59},
  {id: 682, name: "Huyện Trấn Yên", province: 59},
  {id: 683, name: "Huyện Trạm Tấu", province: 59},
  {id: 684, name: "Huyện Lục Yên", province: 59},
  {id: 35, name: "Thành phố Vĩnh Long", province: 60},
  {id: 36, name: "Huyện Long Hồ", province: 60},
  {id: 37, name: "Huyện Mang Thít", province: 60},
  {id: 38, name: "Thị xã Bình Minh", province: 60},
  {id: 39, name: "Huyện Trà Ôn", province: 60},
  {id: 40, name: "Huyện Tam Bình", province: 60},
  {id: 41, name: "Huyện Vũng Liêm", province: 60},
  {id: 739, name: "Huyện Bình Tân", province: 60},
  {id: 85, name: "Thành phố Thủ Dầu Một", province: 61},
  {id: 86, name: "Huyện Bàu Bàng", province: 61},
  {id: 87, name: "Huyện Bắc Tân Uyên", province: 61},
  {id: 88, name: "Thị xã Thuận An", province: 61},
  {id: 89, name: "Thị xã Dĩ An", province: 61},
  {id: 90, name: "Huyện Phú Giáo", province: 61},
  {id: 91, name: "Huyện Dầu Tiếng", province: 61},
  {id: 751, name: "Thị xã Bến Cát", province: 61},
  {id: 752, name: "Thị xã Tân Uyên", province: 61},
  {id: 204, name: "Thị xã Gia Nghĩa", province: 62},
  {id: 205, name: "Huyện Đắk Song", province: 62},
  {id: 206, name: "Huyện Cư Jút", province: 62},
  {id: 207, name: "Huyện Krông Nô", province: 62},
  {id: 208, name: "Huyện Đắk Glong", province: 62},
  {id: 209, name: "Huyện Đắk Mil", province: 62},
  {id: 210, name: "Huyện Đắk R'lấp", province: 62},
  {id: 718, name: "Huyện Tuy Đức", province: 62},
  {id: 211, name: "Thành phố Sa Đéc", province: 63},
  {id: 212, name: "Thành phố Cao Lãnh", province: 63},
  {id: 213, name: "Huyện Tân Hồng", province: 63},
  {id: 214, name: "Huyện Hồng Ngự", province: 63},
  {id: 215, name: "Huyện Tam Nông", province: 63},
  {id: 216, name: "Huyện Thanh Bình", province: 63},
  {id: 217, name: "Huyện Cao Lãnh", province: 63},
  {id: 218, name: "Huyện Lấp Vò", province: 63},
  {id: 219, name: "Huyện Tháp Mười", province: 63},
  {id: 230, name: "Huyện Lai Vung", province: 63},
  {id: 231, name: "Huyện Châu Thành", province: 63},
  {id: 740, name: "Thị xã Hồng Ngự", province: 63},
  {id: 344, name: "Thành phố Hưng Yên", province: 64},
  {id: 345, name: "Huyện Kim Động", province: 64},
  {id: 346, name: "Huyện Ân Thi", province: 64},
  {id: 347, name: "Huyện Khoái Châu", province: 64},
  {id: 348, name: "Huyện Yên Mỹ", province: 64},
  {id: 349, name: "Huyện Tiên Lữ", province: 64},
  {id: 350, name: "Huyện Phù Cừ", province: 64},
  {id: 351, name: "Huyện Mỹ Hào", province: 64},
  {id: 352, name: "Huyện Văn Lâm", province: 64},
  {id: 353, name: "Huyện Văn Giang", province: 64},
  {id: 375, name: "Thành phố Kon Tum", province: 65},
  {id: 376, name: "Huyện Đắk Glei", province: 65},
  {id: 377, name: "Huyện Ngọc Hồi", province: 65},
  {id: 378, name: "Huyện Đắk Tô", province: 65},
  {id: 379, name: "Huyện Sa Thầy", province: 65},
  {id: 380, name: "Huyện Kon Plông", province: 65},
  {id: 381, name: "Huyện Đắk Hà", province: 65},
  {id: 382, name: "Huyện Kon Rẫy", province: 65},
  {id: 383, name: "Huyện Tu Mơ Rông", province: 65},
  {id: 436, name: "Thành phố Ninh Bình", province: 66},
  {id: 437, name: "Thị xã Tam Điệp", province: 66},
  {id: 438, name: "Huyện Nho Quan", province: 66},
  {id: 439, name: "Huyện Gia Viễn", province: 66},
  {id: 450, name: "Huyện Hoa Lư", province: 66},
  {id: 451, name: "Huyện Yên Mô", province: 66},
  {id: 452, name: "Huyện Kim Sơn", province: 66},
  {id: 453, name: "Huyện Yên Khánh", province: 66},
  {id: 580, name: "Thành phố Sơn La", province: 67},
  {id: 581, name: "Huyện Quỳnh Nhai", province: 67},
  {id: 582, name: "Huyện Mường La", province: 67},
  {id: 583, name: "Huyện Thuận Châu", province: 67},
  {id: 584, name: "Huyện Bắc Yên", province: 67},
  {id: 585, name: "Huyện Phù Yên", province: 67},
  {id: 586, name: "Huyện Mai Sơn", province: 67},
  {id: 587, name: "Huyện Yên Châu", province: 67},
  {id: 588, name: "Huyện Sông Mã", province: 67},
  {id: 589, name: "Huyện Mộc Châu", province: 67},
  {id: 590, name: "Huyện Sốp Cộp", province: 67},
  {id: 746, name: "Huyện Vân Hồ", province: 67}
];

export default DISTRICT;
