const PROVINCE = [
    {id: 1, value: 1, name: "Hồ Chí Minh", level: 1, isLeaf: false},
    {id: 20, name: "Đồng Nai", level: 1, isLeaf: false},
    {id: 15, name: "Cần Thơ", level: 1, isLeaf: false},

    {id: 3, name: "An Giang", level: 1, isLeaf: false},
    {id: 58, name: "Bà Rịa–Vũng Tàu", level: 1, isLeaf: false},
    {id: 5, name: "Bắc Kạn", level: 1, isLeaf: false},
    {id: 6, name: "Bắc Giang", level: 1, isLeaf: false},
    {id: 7, name: "Bạc Liêu", level: 1, isLeaf: false},
    {id: 8, name: "Bắc Ninh", level: 1, isLeaf: false},
    {id: 9, name: "Bến Tre", level: 1, isLeaf: false},
    {id: 61, name: "Bình Dương", level: 1, isLeaf: false},
    {id: 11, name: "Bình Định", level: 1, isLeaf: false},
    {id: 12, name: "Bình Phước", level: 1, isLeaf: false},
    {id: 13, name: "Bình Thuận", level: 1, isLeaf: false},

    {id: 14, name: "Cà Mau", level: 1, isLeaf: false},
    {id: 16, name: "Cao Bằng", level: 1, isLeaf: false},
    {id: 17, name: "Đà Nẵng", level: 1, isLeaf: false},
    {id: 18, name: "Đắk Lắk", level: 1, isLeaf: false},
    {id: 62, name: "Đắk Nông", level: 1, isLeaf: false},
    {id: 19, name: "Điện Biên", level: 1, isLeaf: false},
    {id: 63, name: "Đồng Tháp", level: 1, isLeaf: false},
    {id: 21, name: "Gia Lai", level: 1, isLeaf: false},

    {id: 22, name: "Hà Giang", level: 1, isLeaf: false},
    {id: 23, name: "Hà Nam", level: 1, isLeaf: false},
    {id: 2, name: "Hà Nội", level: 1, isLeaf: false},
    {id: 24, name: "Hậu Giang", level: 1, isLeaf: false},
    {id: 25, name: "Hà Tĩnh", level: 1, isLeaf: false},
    {id: 26, name: "Hải Dương", level: 1, isLeaf: false},
    {id: 27, name: "Hải Phòng", level: 1, isLeaf: false},
    {id: 28, name: "Hòa Bình", level: 1, isLeaf: false},
    {id: 52, name: "Huế", level: 1, isLeaf: false},
    {id: 64, name: "Hưng Yên", level: 1, isLeaf: false},
    {id: 30, name: "Khánh Hòa", level: 1, isLeaf: false},
    {id: 56, name: "Kiên Giang", level: 1, isLeaf: false},
    {id: 65, name: "Kon Tum", level: 1, isLeaf: false},
    {id: 32, name: "Lai Châu", level: 1, isLeaf: false},
    {id: 33, name: "Lâm Đồng", level: 1, isLeaf: false},
    {id: 34, name: "Lạng Sơn", level: 1, isLeaf: false},
    {id: 35, name: "Lào Cai", level: 1, isLeaf: false},
    {id: 36, name: "Long An", level: 1, isLeaf: false},
    {id: 37, name: "Nam Định", level: 1, isLeaf: false},
    {id: 38, name: "Nghệ An", level: 1, isLeaf: false},
    {id: 66, name: "Ninh Bình", level: 1, isLeaf: false},
    {id: 39, name: "Ninh Thuận", level: 1, isLeaf: false},
    {id: 40, name: "Phú Thọ", level: 1, isLeaf: false},
    {id: 41, name: "Phú Yên", level: 1, isLeaf: false},
    {id: 42, name: "Quảng Bình", level: 1, isLeaf: false},
    {id: 43, name: "Quảng Nam", level: 1, isLeaf: false},
    {id: 44, name: "Quảng Ngãi", level: 1, isLeaf: false},
    {id: 45, name: "Quảng Ninh", level: 1, isLeaf: false},
    {id: 46, name: "Quảng Trị", level: 1, isLeaf: false},
    {id: 47, name: "Sóc Trăng", level: 1, isLeaf: false},
    {id: 67, name: "Sơn La", level: 1, isLeaf: false},
    {id: 48, name: "Tây Ninh", level: 1, isLeaf: false},
    {id: 49, name: "Thái Bình", level: 1, isLeaf: false},
    {id: 50, name: "Thái Nguyên", level: 1, isLeaf: false},
    {id: 51, name: "Thanh Hóa", level: 1, isLeaf: false},

    {id: 53, name: "Tiền Giang", level: 1, isLeaf: false},
    {id: 54, name: "Trà Vinh", level: 1, isLeaf: false},
    {id: 55, name: "Tuyên Quang", level: 1, isLeaf: false},
    {id: 60, name: "Vĩnh Long", level: 1, isLeaf: false},
    {id: 57, name: "Vĩnh Phúc", level: 1, isLeaf: false},
    {id: 59, name: "Yên Bái", level: 1, isLeaf: false}
];

export default PROVINCE;
